export var filterwoorden = new Set(['de', 'een', 'van', 'een', 'het', 'in', 'voor', 'te', 'op', 'en', 'we', 'met', 'om','-','dat', 'is','aan', 'die',
'aan', 'worden','ook','maar','bij','als', 'zijn', 'niet', 'je', 'kunner', 'er', 'of', 'moet', 'naar', 'groenlinks', 'd66', 'pvv', 'vvd', 'wordt',
'meer', 'hun', 'krijgen', 'over', 'ons', 'ze', 'uit','deze', 'zoals', 'geen', 'hebben', 'verkiezingsprogramma', 'door', 'kunnen', 'dit', 'onze', 'zo', 'bijvoorbeeld',
 'kan', 'dit', 'maken', 'gaan','wij', 'willen','zich', 'komt', 'tot', 'cda', '50plus', 'bij1', 'cu', 'christenunie', 'denk', 'fvd',
'ja21','pvda','pvdd','pvv', 'sgp', 'sp', 'volt', '\\-', 'ja', ':', 'dan', 'nederland', 'uw', 'wil', 'wat', 'heeft', 'waar', 'd', '-', 'nederlandse',
'moeten','mensen', 'daarom', 'veel', 'daarom', 'komen', '&', 'versie', 'nog', 'gaat', 'al', 'u', 'weer', 'uverkiezingsprogramma', 'partij',
'hoofdstuk', 'cda-verkiezingsprogramma', 'plus', 'blijven','alle','steeds','ten','zetten', 'tegen', 'zij', 'eigen', 'andere',
'land', 'maart', 'onder', 'tussen', 'iedereen', 'goed', 'doen', 'piratenpartij', 'programma', 'overheid', 'kamerverkiezingen', 'waarbij', 'wel',
'komende','dient', 'staat', 'zodat', 'grote', 'laat', 'jaar', 'jaren', 'alleen', 'zaken', 'dus', 'nodig', 'mogelijk',
'goede', 'v', 'e', 'via', 'lees', 'daarbij','binnen', 'waarin', 'politieke','hoe','vaak', 'nu', 'plaats', 'na', 'telt',
'wwwstemvoltnlverkiezingsprogramma', 'procent', 'voortaan','nu', 'voorkomen']);