export var filterzinnen = new Array('partij voor de dieren', 'De kracht van PLUS', 'Nu doorpakken', 
'CHRISTENUNIE VERKIEZINGSPROGRAMMA 2021-2025 KIEZEN VOOR WAT ECHT TELT', 'KIEZEN VOOR WAT ECHT TELT',
'Een nieuw begin - Laat iedereen vrij, maar niemand vallen.', 'De digitale versie lees je op d66.nl/eennieuwbegin','Programma thema’s',
'Verkiezingsprogramma PVV 2021 - 2025 Het gaat om u', 
'VERKIEZINGSPROGRAMMA VAN DE SP 17 MAART 2021 STEL EEN DAAD', 'Verkiezingsprogramma 2021 -2025 - Ons nieuwe verhaal', 
'Een sterke en eerlijke economie', 'Een veilige en verantwoordelijke samenleving', 'Thuis', 
'VERKIEZINGSPROGRAMMA PARTIJ VOOR DE DIEREN TWEEDE KAMERVERKIEZINGEN 2021', 'VERKIEZINGSPROGRAMMA VAN DE SP 17 MAART 2021 STEL EEN DAAD',
'Een betrouwbare en dienstbare overheid', 'Een land van waarden en tradities', 'Een land van waarden en tradities',
'Inclusie en Acceptatie', 'Zorg en Volksgezondheid', 'Wonen en Volkshuisvesting', 'Buitenland, Defensie en Ontwikkelingssamenwerking',
'Migratie en Asiel', 'Justitie, Veiligheid en Rechtsstaat', 'Economie, Mobiliteit en Infrastructuur', 'Klimaat en Energie',
'Hoofdstuk 1: Soevereiniteit & Democratie', 'Hoofdstuk 2: Immigratie & Identiteit', 'Hoofdstuk 3: EU, Defensie, Buitenlandse Zaken',
'Hoofdstuk 4: Economie en Sociale Zaken', 'Hoofdstuk 5: Klimaat, Landbouw & Innovatie', 'Hoofdstuk 6: Zorg',
'Hoofdstuk 7: Onderwijs, Cultuur en Wereldbeschouwing', 'Verkiezingsprogramma 2021 -2025 - Volksgezondheid en Zorg', 
'Verkiezingsprogramma 2021 -2025 - Economie en Ondernemen', 'Verkiezingsprogramma 2021 -2025 - Werk en Zekerheid', 
'Verkiezingsprogramma 2021 -2025 - Buitenland en Defensie', 'Verkiezingsprogramma 2021 -2025 - Onderwijs en Vrijheid',
'Verkiezingsprogramma 2021 -2025 - Migratie en Integratie', 'Verkiezingsprogramma 2021 -2025 - Justitie en Veiligheid', 
'Verkiezingsprogramma 2021 -2025 - Klimaat en Duurzaamheid', 'Verkiezingsprogramma 2021 -2025 - Wonen en Vervoer',
'Verkiezingsprogramma 2021 -2025 - Landbouw en Natuur', 'Verkiezingsprogramma 2021 -2025 - Overheid en Democratie',
'Partij voor de Dieren', 'KIEZEN  VOOR WAT ECHT TELT');